package group.phorus.auth.commons.bdd.app.dtos

import java.util.*

data class DocumentDTO(
    var title: String? = null,
    var content: String? = null,
    var sensitiveInfo: String? = null,
    var restrictedData: String? = null,
    var fieldOnlyData: String? = null,
    var readOnlyField: String? = null,
    var updateOnlyField: String? = null,
    var multiAuthField: String? = null,
    var authContextField: String? = null,
    var httpContextField: String? = null,
    var entityContextField: String? = null,
    var templateField: String? = null,
    var valueMatchField: String? = null,
    var onlyMatchField: String? = null,
    var onlyValueField: String? = null,
    var getHandlerField: String? = null,
    var postHandlerField: String? = null,
    var noAuthField: String? = null,
    var timeoutField: String? = null,
    var networkErrorField: String? = null,
    var invalidUrlField: String? = null,
    var databaseField: String? = null,
    var validationField: String? = null,
    var chainedField: String? = null,
    var validTemplateField: String? = null,
    var invalidTemplateField: String? = null,
    var nestedTemplateField: String? = null,
    var orgDataField: String? = null,
    var orgPermissionField: String? = null,
    var orgRoleField: String? = null,
    var setupField: String? = null,
    var responseField: String? = null,
    var handlerField: String? = null,
    var invalidContextField: String? = null,
    var missingFieldRef: String? = null,
    var errorHandlerField: String? = null,
    var saveToField: String? = null,
    var precedenceField: String? = null,
    var securityField: String? = null
)

data class DocumentResponse(
    var id: UUID? = null,
    var title: String? = null,
    var content: String? = null,
    var ownerId: UUID? = null,
    var departmentId: String? = null,
    var financialData: String? = null,
    var sensitiveInfo: String? = null,
    var restrictedData: String? = null,
    var fieldOnlyData: String? = null,
    var readOnlyField: String? = null,
    var updateOnlyField: String? = null,
    var multiAuthField: String? = null,
    var authContextField: String? = null,
    var httpContextField: String? = null,
    var entityContextField: String? = null,
    var templateField: String? = null,
    var valueMatchField: String? = null,
    var onlyMatchField: String? = null,
    var onlyValueField: String? = null,
    var getHandlerField: String? = null,
    var postHandlerField: String? = null,
    var noAuthField: String? = null,
    var timeoutField: String? = null,
    var networkErrorField: String? = null,
    var invalidUrlField: String? = null,
    var databaseField: String? = null,
    var validationField: String? = null,
    var chainedField: String? = null,
    var validTemplateField: String? = null,
    var invalidTemplateField: String? = null,
    var nestedTemplateField: String? = null,
    var orgDataField: String? = null,
    var orgPermissionField: String? = null,
    var orgRoleField: String? = null,
    var setupField: String? = null,
    var responseField: String? = null,
    var handlerField: String? = null,
    var invalidContextField: String? = null,
    var missingFieldRef: String? = null,
    var nullField: String? = null,
    var circularRefField: String? = null,
    var deepNestedField: String? = null,
    var errorHandlerField: String? = null,
    var saveToField: String? = null,
    var precedenceField: String? = null,
    var securityField: String? = null
)