package group.phorus.auth.commons.bdd.app.services.impl

import group.phorus.auth.commons.bdd.app.dtos.AuthResponse
import group.phorus.auth.commons.bdd.app.dtos.LoginData
import group.phorus.auth.commons.bdd.app.model.Device
import group.phorus.auth.commons.bdd.app.model.User
import group.phorus.auth.commons.bdd.app.repositories.DeviceRepository
import group.phorus.auth.commons.bdd.app.repositories.UserRepository
import group.phorus.auth.commons.bdd.app.services.AuthService
import group.phorus.auth.commons.dtos.AccessToken
import group.phorus.auth.commons.dtos.TokenType
import group.phorus.auth.commons.services.Authenticator
import group.phorus.auth.commons.services.TokenFactory
import group.phorus.exception.handling.NotFound
import group.phorus.exception.handling.Unauthorized
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.springframework.security.crypto.scrypt.SCryptPasswordEncoder
import org.springframework.stereotype.Service
import kotlin.jvm.optionals.getOrElse
import kotlin.jvm.optionals.getOrNull

@Service
class AuthServiceImpl(
    private val encoder: SCryptPasswordEncoder,
    private val tokenFactory: TokenFactory,
    private val userRepository: UserRepository,
    private val deviceRepository: DeviceRepository,
    private val authenticator: Authenticator,
) : AuthService {
    private val headerPrefix = "Bearer "

    override suspend fun login(loginData: LoginData): AuthResponse {
        val user = withContext(Dispatchers.IO) {
            userRepository.findByEmail(loginData.email!!).orElseThrow {
                NotFound("User not found with email: ${loginData.email}")
            }
        }

        return login(user, loginData)
    }

    override suspend fun refreshAccessToken(refreshToken: String): AccessToken {
        if (refreshToken.length <= headerPrefix.length) throw Unauthorized("Invalid authorization header size")
        if (!refreshToken.contains(headerPrefix)) throw Unauthorized("Bearer token not found")

        val jwt = refreshToken.substring(headerPrefix.length)

        val authData = authenticator.authenticate(jwt)
        if (authData.tokenType !== TokenType.REFRESH_TOKEN)
            throw Unauthorized("Invalid refresh token")

        val device = withContext(Dispatchers.IO) {
            deviceRepository.findByUserIdAndJTI(authData.userId, authData.jti).getOrNull()
        }
        if (device == null || device.disabled) throw Unauthorized("Invalid refresh token, please log in again")

        val accessToken = tokenFactory.createAccessToken(authData.userId, listOf("admin"), authData.properties)
        val accessTokenJTI = authenticator.parseClaims(accessToken.token).payload.id

        device.accessTokenJTI = accessTokenJTI
        withContext(Dispatchers.IO) {
            deviceRepository.save(device)
        }

        return accessToken
    }


    private suspend fun login(user: User, loginData: LoginData): AuthResponse {
        if (!encoder.matches(loginData.password, user.passwordHash))
            throw Unauthorized("Authentication Failed. Email or Password not valid.")

        // Here you can save any extra properties inside the token and refresh token
        // Try to always set the same properties, as the access tokens generated by a refresh token
        // will inherit its properties
        val properties = mapOf("tokenThingy" to true.toString())

        // We are setting the privileges with "admin" as an example, please take the privileges from a privileges table
        val accessToken = tokenFactory.createAccessToken(user.id, listOf("admin"), properties)
        val refreshToken = tokenFactory.createRefreshToken(user.id, loginData.expires, properties)

        val accessTokenJTI = authenticator.parseClaims(accessToken.token).payload.id
        val refreshTokenJTI = authenticator.parseClaims(refreshToken).payload.id

        withContext(Dispatchers.IO) {
            deviceRepository.findByNameAndUserId(loginData.device!!, user.id)
        }.getOrElse {
            Device(
                name = loginData.device,
                user = user,
            )
        }.apply {
            this.accessTokenJTI = accessTokenJTI
            this.refreshTokenJTI = refreshTokenJTI
            disabled = false
        }.let { deviceRepository.save(it) }

        return AuthResponse(accessToken, refreshToken)
    }
}